development:
  cloud_name: hxdeddjt1
  api_key: '165831714683969'
  api_secret: AgDvKJ9GOCZYgGe86iIiim_luHg
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hxdeddjt1
  api_key: '165831714683969'
  api_secret: AgDvKJ9GOCZYgGe86iIiim_luHg
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hxdeddjt1
  api_key: '165831714683969'
  api_secret: AgDvKJ9GOCZYgGe86iIiim_luHg
  enhance_image_tag: true
  static_image_support: false
